site_name: PyMatillion

plugins:
  - mkdocstrings
  - mkdocs-jupyter:
      include: ['*.ipynb']
      ignore_h1_titles: True
      include_source: True

theme:
  name: material

nav:
  - Reference Docs: reference.md
  - Usage Examples: pymatillion_examples.ipynb